### PR TITLE
Created sidebar with movie titles and times which are shown  that days date 

### LINKED ISSUE #8: Sidebar
Description:
Create a sidebar on the right side on page with viewing times for todays date.

User story:

As a user I want to be able to see which movies that are shown during the day

Acceptance criteria:
- Visible side bar on start page with dates and times and movie titles.
- Each movie title should be a link to the info page about that movie

Dependencies:
- #17 

Design: 

https://www.figma.com/file/vhNtZfxUiEfTYAYr6yaExM/VadSomHelst?node-id=0%3A1&t=cYaYV5PdLwQegbag-0

### PR DESCRIPTION
**Pull request by matodorovic**
### Description
This PR adds sidebar to start page and restaurant page and minor fixes.

### Screenshots
Skärmavbild 2023-01-04 kl  17 31 33
Skärmavbild 2023-01-04 kl  18 14 12

Skärmavbild 2023-01-04 kl  18 14 04

### Changes
- Adds sidebar with styling for desktop (not visible for mobile view)
- Adds id and underline in nav bar to show user a location 
-  Changes date format to be able to use build-in date functions
- Fixes image for movies look in start page
- Fixes location.pathname to show movies on start page
- Adds location.pathname to show sidebar for start page and restaurant page

### Issues:
#8

### CODE REVIEW

**Comment by rfabricioflores** [comment]
Looks good! Simple and useful :D

**Comment by matodorovic** [comment]
Changed to show time HH:MM without seconds. 
Skärmavbild 2023-01-04 kl  19 19 58

**Review by jakobpalmborg — APPROVED** [review]
Looks good!

**Review by DanneCarlson — APPROVED** [review]
Looks good and works just fine!

**Pull request merged**
