### PR TITLE
About us initial page

### LINKED ISSUE #14: About us - Initial Page
Initial static About Us page. Create html page with content and basic css.

As a user i want a page to read some info about the cinema and its background.

### PR DESCRIPTION
**Pull request by jakobpalmborg**
I have created the about us page with content and styling. 

image

### CODE REVIEW

**Comment by mkor92** [comment]
Check the conflicts, other than that it looks great!

**Review by mkor92 — APPROVED** [review]
All looks great! Added links in header menu and solved a CSS conflict.

**Review by DanneCarlson — APPROVED** [review]
I took a look at it and can't find anything to comment, it all looks good :) I made a pull and tried it locally and it worked just fine.

**Review by matodorovic — APPROVED** [review]
Nice simple site with info. 👍  Works fine locally.

**Pull request merged**
