### PR TITLE
Nav bar for desktop and mobile menu fix & overflow fix & favicon

### LINKED ISSUE #34: Navmenu - Dropdown fix on mobile
Description: 
- nav menu takes too much space on mobile view
- Fix so it only shows button Meny
- change font size on navigation menu and footer

Acceptance criteria:
- When clicking on meny button it opens navigation menu with 5 alternatives:
- - Filmer
- - Salonger
- - Restaurang
- - Events
- - Kontakt

- Visible smaller font size for footer and navigation menu

Design:

https://www.figma.com/file/vhNtZfxUiEfTYAYr6yaExM/VadSomHelst?node-id=0%3A1&t=IA25Ar3iahXA9S6S-0

### LINKED ISSUE #70: Fix movies on startpage scroll
Description:
Movies on start page are srolling with whole site instead to scroll only movies.

### LINKED ISSUE #72: Events page - initial page
Create html boilerplate for events page.

As a user I want to see the events page

### LINKED ISSUE #73: Fav icon for Luleå Bio site
Description:
- Create a icon which will be used to be icon for site

User story:
- As a user when I have many sites open I want to be able to see miniature bio icon on tab to be able to recognize the site between many tabs open

### PR DESCRIPTION
**Pull request by matodorovic**
### Description
This PR changes navigation bar from hover dropdown to under category like in movies page, adds events html page and adds favicon.

### Screenshots
Skärmavbild 2023-01-08 kl  23 59 27
Skärmavbild 2023-01-08 kl  23 59 17
Skärmavbild 2023-01-08 kl  23 59 04
Skärmavbild 2023-01-09 kl  00 29 26
Skärmavbild 2023-01-09 kl  00 35 37
Skärmavbild 2023-01-09 kl  00 45 07

Screen recordings showing overflow on start page and mobile menu working:

https://user-images.githubusercontent.com/90763011/211224710-c5c9ec29-1784-477c-8524-74036f0d175b.mov
https://user-images.githubusercontent.com/90763011/211224725-13e5cdf2-1d02-4c97-80d1-1af49e08f1b0.mov

### Changes
- Fixes mobile nav menu issue by changing navigation menu
- Adds id and underline in nav bar to show user a location for events
- Creates a evnet html page
- Fixes overflow for movies on start page mobile view
- Adds favicon folder och links to all html pages

### Issues:
#70 
#72 
#73 
#34

### CODE REVIEW

**Review by mkor92 — APPROVED** [review]
Nice work Marta! I think it looks much better now.

**Review by DanneCarlson — CHANGES_REQUESTED** [review]
Good work, Marta! Overall it looks good. One small detail came to my mind though; when you're on a salon site (for example Salong A) you should be able to switch between Salong A and B and vice versa, so you don't have to go back to the Salons.html to do that?

**Comment by matodorovic** [comment]
> Good work, Marta! Overall it looks good. One small detail came to my mind though; when you're on a salon site (for example Salong A) you should be able to switch between Salong A and B and vice versa, so you don't have to go back to the Salons.html to do that?

I was thinking to do that but wasn't sure. Thanks for your feedback! I will take care of it and than re-open my PR.

**Comment by matodorovic** [comment]
### Changes:
 - Added under menu for Salon A and B html sites like requested

### Screenshots
Skärmavbild 2023-01-11 kl  23 50 05
Skärmavbild 2023-01-11 kl  23 53 57

**Review by DanneCarlson — APPROVED** [review]
Thanx, nice work with the manu!

**Pull request merged**
