### PR TITLE
Minor fix css

### LINKED ISSUE #39: Minor fix scss

### PR DESCRIPTION
**Pull request by rfabricioflores**
Remove fixed positioning for footer
Fix max-width for all the sections using reusable classes
Fix about us site styles
Fix other bugs

### CODE REVIEW

**Review by jakobpalmborg — APPROVED** [review]
Great! It looks good. Just one thing about the footer - its a empty space below the footer when I view it. like this:

image

**Review by matodorovic — COMMENTED** [review]
In desktop view looks good but wen I look in mobile view it looks like this. Empty space. Can u try to fix it before we merge it in?

Skärmavbild 2022-12-30 kl  11 30 06

**Review by matodorovic — APPROVED** [review]
Just that small thing with white space otherwise 👍

**Comment by DanneCarlson** [comment]
> Great! It looks good. Just one thing about the footer - its a empty space below the footer when I view it. like this:
> 
> image

Hmm... downloaded and checked. I can't see the problem with empty space, but maybe it's already fixed?

**Review by matodorovic — APPROVED** [review]
Great! It is just to solve conflicts and merge branch into main

**Pull request merged**
